# Generated by Django 3.0.5 on 2020-09-26 10:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineParking', '0002_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='place',
            field=models.CharField(default=datetime.datetime(2020, 9, 26, 10, 41, 4, 195405, tzinfo=utc), max_length=50),
            preserve_default=False,
        ),
    ]
